
package com.exemple.generate;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebService", targetNamespace = "http://server.dobrodey.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.dobrodey.ru/HelloWebService/addRequest", output = "http://server.dobrodey.ru/HelloWebService/addResponse")
    public int add(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.exemple.generate.StringArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.dobrodey.ru/HelloWebService/getListRequest", output = "http://server.dobrodey.ru/HelloWebService/getListResponse")
    public StringArray getList(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.dobrodey.ru/HelloWebService/getHelloStringRequest", output = "http://server.dobrodey.ru/HelloWebService/getHelloStringResponse")
    public String getHelloString(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

    /**
     * 
     * @return
     *     returns com.exemple.generate.Users
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://server.dobrodey.ru/HelloWebService/getUserRequest", output = "http://server.dobrodey.ru/HelloWebService/getUserResponse")
    public Users getUser();

}
